### ISSUE TITLE
[Bug] aws 프로덕션 설정에서 datasource url을 찾지 못하는 문제

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-19/todaktodak-api#105]
### 📍 문제 상황

백엔드 애플리케이션이 변수가 설정됐음에도 불구하고 실행에 계속 실패합니다.
- Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
- If you have database settings to be loaded from a particular profile you may need to activate it (the profiles prod are currently active).

### 🎯 해결 방법

애플리케이션을 실행할때 명확한 프로필을 제시해서 실행환경을 고정합니다.

### ⭐️ 중요도

상 - 당장 해결해야 다음 작업이 진행가능합니다.

**Comment by Urchinode** [comment]
```
the profiles prod are currently active
```
~~이 로그를 보면 `prod` 프로필로 실행이 된 것 같습니다.
저희가 profile을 `local`로 사용중인데, `local` 프로필로 실행해보실수 있을까요?
이 부분을 말씀안드렸네요 😭~~

```
SPRING_PROFILES_ACTIVE=local java $(cat .env.local| xargs -I {} echo "-D{}" ) -jar ./build/libs/todaktodak-api-0.0.1-SNAPSHOT.jar
```
~~java 로 스프링부트 실행할때 `SPRING_PROFILES_ACTIVE=local` 처럼 프로필을 지정하면 될 것 같습니다 😃~~

**아래 에반님 코멘트 확인부탁드립니다**

**Comment by kchsoft** [comment]
로컬(Window/mac) 에서 gradle 의존성에
> implementation group: 'me.paulschwarz', name: 'spring-dotenv', version: '4.0.0'

를 추가

```.env.back``` 이름 변경 -> ```todak.properties```

```applicatoin.yaml``` 에서 설정 추가

```
spring:
  config:
    import: file:todak.properties
    
```


를 하면 gradle로 clean build 후에 기본 옵션으로 jar 를 실행 시키면 동작하는 것 확인하였습니다.

```java -jar ./~SNAPSHOT.jar```
